const DATA=window.QENTRA_DATA;let track='STET';
const $=s=>document.querySelector(s),body=document.body,toast=$('#toast');
const saved=localStorage.getItem('qentra-theme');if(saved==='dark'){body.classList.add('dark');$('#themeToggle').textContent='☀'}
$('#themeToggle').addEventListener('click',()=>{body.classList.toggle('dark');const dark=body.classList.contains('dark');$('#themeToggle').textContent=dark?'☀':'☾';localStorage.setItem('qentra-theme',dark?'dark':'light')});
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(window.qToast);window.qToast=setTimeout(()=>toast.classList.remove('show'),2400)}
function setTrack(next){track=next;const d=DATA[track],qs=d;const years=[...new Set(qs.map(q=>q.year))].sort((a,b)=>b-a);$('#trackLabel').textContent=track;$('#heroTrack').textContent=`${track} · Computer Science`;$('#questionCount').textContent=`${qs.length} loaded questions`;$('#coverage').textContent=`${years.length} years`;$('#analysisTitle').textContent=`${track} concept recurrence`;$('#dataStatus').textContent='DEMO DATA';$('#dataMode').textContent='Demo fixtures · verification pending';document.querySelectorAll('.exam-card').forEach(c=>c.classList.remove('active'));$(`#${track.toLowerCase()}Card`).classList.add('active');buildFilters(years);renderAnalysis();renderQuestions();showToast(`${track} Computer Science workspace selected`)}
function buildFilters(years){$('#yearFilter').innerHTML='<option value="all">All years</option>'+years.map(y=>`<option>${y}</option>`).join('');$('#topicFilter').innerHTML='<option value="all">All topics</option>'+[...new Set(DATA[track].map(q=>q.topic))].sort().map(t=>`<option>${t}</option>`).join('')}
function renderAnalysis(){const qs=DATA[track],counts={};qs.forEach(q=>counts[q.topic]=(counts[q.topic]||0)+1);const max=Math.max(...Object.values(counts),1);$('#topicBars').innerHTML=Object.entries(counts).sort((a,b)=>b[1]-a[1]).map(([t,n])=>`<div class="bar-row"><label>${t}</label><div><i style="width:${Math.round(n/max*100)}%"></i></div><b>${n}/${qs.length}</b></div>`).join('');const sub={};qs.forEach(q=>sub[q.sub]=(sub[q.sub]||0)+1);const typeWeight={exact:4,reframed:3,concept:2,new:1};const score=n=>qs.filter(q=>q.sub===n).reduce((s,q)=>s+typeWeight[q.type],0);$('#priorityList').innerHTML=Object.entries(sub).sort((a,b)=>score(b[0])-score(a[0])).slice(0,5).map(([name,n],i)=>`<div><span class="rank">${String(i+1).padStart(2,'0')}</span><strong>${name}</strong><em>${score(name)>=4?'HIGH':'MED'}</em></div>`).join('')}
function filtered(){const y=$('#yearFilter').value,t=$('#topicFilter').value,ty=$('#typeFilter').value;return DATA[track].filter(q=>(y==='all'||String(q.year)===y)&&(t==='all'||q.topic===t)&&(ty==='all'||q.type===ty))}
const labels={exact:'EXACT PYQ',reframed:'REFRAMED PYQ',concept:'SAME CONCEPT',new:'NEW'};
function renderQuestions(){const qs=filtered();$('#filterCount').textContent=`${qs.length} questions`;$('#questionList').innerHTML=qs.map(q=>`<article class="question-card"><div class="question-meta"><span>${track} · ${q.year}</span><b class="type-${q.type}">${labels[q.type]}</b></div><h4>${q.question}</h4><div class="options">${q.options.map((o,i)=>`<span>${String.fromCharCode(65+i)}. ${o}</span>`).join('')}</div><div class="question-foot"><span>${q.topic} · ${q.sub}</span><button class="reveal" data-answer="${q.id}">Reveal answer</button></div><div class="answer" id="answer-${q.id}"><strong>Correct answer:</strong> ${q.options[q.answer]}<small>Source: ${q.source}</small></div></article>`).join('')||'<div class="panel empty">No questions match these filters.</div>';document.querySelectorAll('.reveal').forEach(b=>b.addEventListener('click',()=>{const a=$(`#answer-${b.dataset.answer}`);a.classList.toggle('show');b.textContent=a.classList.contains('show')?'Hide answer':'Reveal answer'}))}
['yearFilter','topicFilter','typeFilter'].forEach(id=>$('#'+id).addEventListener('change',renderQuestions));
document.querySelectorAll('[data-exam]').forEach(b=>b.addEventListener('click',()=>setTrack(b.dataset.exam)));
$('#mockBtn').addEventListener('click',()=>showToast(`Targeted ${track} mock: ${Math.min(20,DATA[track].length)} loaded questions from priority concepts`));
setTrack('STET');